### ISSUE TITLE
Why template-helper-apidocs

### ISSUE THREAD

**Issue by stefanwalther** [helpers/template-helper-apidocs#2]
Hi @jonschlinkert,

just being curious. Why did you chose to write your own implementation and e.g. not using jsdoc and https://www.npmjs.com/package/jsdoc-to-markdown?

Regards
Stefan

**Comment by jonschlinkert** [comment]
well, good question. this is the first I've heard of the project you linked to, it looks really nice, I'll probably spend some time reviewing it to see if it might work for our needs.

the main reason I decide to create the apidocs stuff was for an idea I had that I still haven't had time to complete, and I really love programming lol.  that said, ironically I actually worked on it over the past couple of days and got about 80% of the way there...  for the longest time I've wanted to be able to do things like `get`, `set` and extend code comments as easily as you can any other javascript object. I also want to be able to lint, update and format code comments via API. not sure if this all makes sense, but I'm excited about the idea of doing it lol.

anyway, this was my motivation for creating snapdragon too, but that project needs some tweaking before it's usable enough to work for this use case.

does that help?

**Comment by stefanwalther** [comment]
Thx for the long answer, sounds interesting. Continue great work.
(Closing this, since this wasn't really an issue).
